### ISSUE TITLE
tools.win -> findFiles

### ISSUE THREAD

**Issue by Krakean** [sergeyreznik/et-engine#1]
Мне кажется эта функция работает немного некорректно,
в том отношении, что закидывает в результаты родительские каталоги при рекурсивном поиске.
Например:
C:\Temp\Bla\123.txt
C:\Temp\Bla2\321.txt
В результатах будут (и именно в таком порядке):
C:\Temp
C:\Temp\Bla
C:\Temp\Bla2
C:\Temp\Bla\123.txt
C:\Temp\Bla2\321.txt

На мой взгляд более ожидаемый результат такой:
C:\Temp\Bla\123.txt
C:\Temp\Bla2\321.txt

Ну или по крайней мере добавить флаг в функцию, чтобы это поведение можно было регулировать.

**Comment by serhii-rieznik** [comment]
Ага, спасибо, провентилируем этот вопрос. 

Сергей

**Comment by serhii-rieznik** [comment]
Починено
