### ISSUE TITLE
Нужные файлы для демок

### ISSUE THREAD

**Issue by Krakean** [sergeyreznik/et-engine#2]
Привет, Сергей
Не удается просмотреть демки движка (напр. scene rendering), потому что жалуется на отсутствие, например, sponza.etm. 
Может ты зальешь все нужные файлы для демок, чтобы скомпилил, запустил, и спокойно смотришь...?

**Comment by serhii-rieznik** [comment]
Там 50 мегабайт, и пихать это в репозиторий смысла нет. Модельку можно качнуть отсюда
https://dl.dropboxusercontent.com/u/23038492/crytek-sponza-etm.zip

**Comment by Krakean** [comment]
> Там 50 мегабайт, и пихать это в репозиторий смысла нет.
> Ну тогда хотя бы вынеси в Readme.md ссылку на весь архив с нужными файлами для демок, а то ж демки движка не поглядеть, и какая-то абсурдная ситуация в результате возникает - код демок есть, а самих ресурсных файлов для них нет.
> Ну это так, с точки зрения простого обывателя :)

**Comment by serhii-rieznik** [comment]
Да, сделаю.
