### ISSUE TITLE
Не компилируется текущая git-версия

### ISSUE THREAD

**Issue by Krakean** [sergeyreznik/et-engine#4]
При попытке скомпилировать scene-rendering в VS2013:
1>------ Build started: Project: windows, Configuration: Release Win32 ------
1>  appevironment.cpp
1>  application.cpp
1>  backgroundthread.cpp
1>  events.cpp
1>  invocation.cpp
1>  pathresolver.cpp
1>  runloop.cpp
1>  camera.cpp
1>  frustum.cpp
1>  collision.cpp
1>  base64.cpp
1>  conversion.cpp
1>  dictionary.cpp
1>  et.cpp
1>  memoryallocator.cpp
1>  objectscache.cpp
1>  stream.cpp
1>  tools.cpp
1>  transformable.cpp
1>  geometry.cpp
1>  Compiling...
1>  rectplacer.cpp
1>  terrain.cpp
1>  terraindata.cpp
1>  ddsloader.cpp
1>  hdrloader.cpp
1>  imageoperations.cpp
1>  imagewriter.cpp
1>  jpegloader.cpp
1>  pngloader.cpp
1>  pvrdecompressor.cpp
1>  pvrloader.cpp
1>  textureloader.cpp
1>  tgaloader.cpp
1>  gestures.cpp
1>  input.cpp
1>  json.cpp
1>  locale.cpp
1>  fbxloader.cpp
1>  Define ET_HAVE_FBX_SDK to compile FBXLoader
1>  objLoader.cpp
1>  capabilities.cpp
1>  Compiling...
1>  framebuffer.cpp
1>  indexbuffer.cpp
1>  opengl.cpp
1>  program.cpp
1>  programfactory.cpp
1>  renderer.cpp
1>  renderstate.cpp
1>  texture.cpp
1>  vertexarrayobject.cpp
1>  vertexbuffer.cpp
1>  application.win.cpp
1>  atomiccounter.win.cpp
1>  criticalsection.win.cpp
1>  input.win.cpp
1>  locale.win.cpp
1>  location.win.cpp
1>  log.win.cpp
1>  memory.win.cpp
1>  mutex.win.cpp
1>  opengl.win.cpp
1>  Compiling...
1>  orientation.win.cpp
1>  platformtools.win.cpp
1>  rendercontext.win-opengl.cpp
1>  thread.win.cpp
1>  threading.win.cpp
1>  tools.win.cpp
1>  primitives.cpp
1>  framebufferfactory.cpp
1>  rendercontext.cpp
1>  rendering.cpp
1>  texturefactory.cpp
1>  textureloadingthread.cpp
1>  vertexbufferfactory.cpp
1>  animation.cpp
1>  baseelement.cpp
1>  cameraelement.cpp
1>  lightelement.cpp
1>  material.cpp
1>  mesh.cpp
1>  particlesystem.cpp
1>  Compiling...
1>  scene3d.cpp
1>  serialization.cpp
1>  storage.cpp
1>  supportmesh.cpp
1>  taskpool.cpp
1>  notifytimer.cpp
1>  sequence.cpp
1>  timedobject.cpp
1>  timerpool.cpp
1>  indexarray.cpp
1>  vertexarray.cpp
1>  vertexdatachunk.cpp
1>  vertexdeclaration.cpp
1>  main.cpp
1>  MainController.cpp
1>  DemoCameraController.cpp
1>  DemoSceneLoader.cpp
1>..\source\renderer\DemoSceneLoader.cpp(38): error C2660: 'et::s3d::BaseElement::deserialize' : function does not take 4 arguments
1>..\source\renderer\DemoSceneLoader.cpp(48): error C3083: 'Scene3dStorage': the symbol to the left of a '::' must be a type
1>..\source\renderer\DemoSceneLoader.cpp(48): error C2039: 'Pointer' : is not a member of 'et::s3d'
1>..\source\renderer\DemoSceneLoader.cpp(48): error C2065: 'Pointer' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(48): error C2146: syntax error : missing ';' before identifier 'storage'
1>..\source\renderer\DemoSceneLoader.cpp(48): error C2065: 'storage' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(48): error C2143: syntax error : missing ';' before ':'
1>..\source\renderer\DemoSceneLoader.cpp(48): error C2143: syntax error : missing ')' before ':'
1>..\source\renderer\DemoSceneLoader.cpp(48): error C2059: syntax error : ')'
1>..\source\renderer\DemoSceneLoader.cpp(49): error C2143: syntax error : missing ';' before '{'
1>..\source\renderer\DemoSceneLoader.cpp(50): error C2065: 'storage' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(50): error C2227: left of '->vertexArrays' must point to class/struct/union/generic type
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(52): error C2065: 'va' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(52): error C2227: left of '->decl' must point to class/struct/union/generic type
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(54): error C3536: 'decl': cannot be used before it is initialized
1>..\source\renderer\DemoSceneLoader.cpp(54): error C2228: left of '.has' must have class/struct/union
1>          type is 'int'
1>..\source\renderer\DemoSceneLoader.cpp(56): error C3536: 'decl': cannot be used before it is initialized
1>..\source\renderer\DemoSceneLoader.cpp(56): error C2228: left of '.push_back' must have class/struct/union
1>          type is 'int'
1>..\source\renderer\DemoSceneLoader.cpp(58): error C3536: 'decl': cannot be used before it is initialized
1>..\source\renderer\DemoSceneLoader.cpp(58): error C2065: 'va' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(58): error C2227: left of '->size' must point to class/struct/union/generic type
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(60): error C2065: 'va' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(60): error C2227: left of '->chunks' must point to class/struct/union/generic type
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(61): error C2065: 'c' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(61): error C2227: left of '->copyTo' must point to class/struct/union/generic type
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(61): error C2227: left of '->usage' must point to class/struct/union/generic type
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(61): error C2228: left of '.reference' must have class/struct/union
1>..\source\renderer\DemoSceneLoader.cpp(63): error C2065: 'storage' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(63): error C2227: left of '->indexArray' must point to class/struct/union/generic type
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(64): error C2065: 'storage' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(64): error C2227: left of '->indexArray' must point to class/struct/union/generic type
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(64): error C2227: left of '->primitivesCount' must point to class/struct/union/generic type
1>..\source\renderer\DemoSceneLoader.cpp(64): error C2661: 'et::primitives::calculateTangents' : no overloaded function takes 2 arguments
1>..\source\renderer\DemoSceneLoader.cpp(68): error C2039: 'vaoWithIdentifiers' : is not a member of 'et::s3d::Scene'
1>          D:\aGIT\GameEngines\et-engine\include\et/scene3d/scene3d.h(24) : see declaration of 'et::s3d::Scene'
1>..\source\renderer\DemoSceneLoader.cpp(70): error C3536: 'vao': cannot be used before it is initialized
1>..\source\renderer\DemoSceneLoader.cpp(70): error C2228: left of '.valid' must have class/struct/union
1>          type is 'int'
1>..\source\renderer\DemoSceneLoader.cpp(72): error C3536: 'vao': cannot be used before it is initialized
1>..\source\renderer\DemoSceneLoader.cpp(73): error C3536: 'vao': cannot be used before it is initialized
1>..\source\renderer\DemoSceneLoader.cpp(73): error C2227: left of '->setVertexBuffer' must point to class/struct/union/generic type
1>          type is 'int'
1>..\source\renderer\DemoSceneLoader.cpp(73): error C2065: 'va' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(73): error C2227: left of '->name' must point to class/struct/union/generic type
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(77): error C2065: 'va' : undeclared identifier
1>..\source\renderer\DemoSceneLoader.cpp(77): error C2228: left of '.reset' must have class/struct/union
1>          type is 'unknown-type'
1>..\source\renderer\DemoSceneLoader.cpp(100): error C2039: 'StorageFormat_HumanReadableMaterials' : is not a member of 'et::s3d'
1>..\source\renderer\DemoSceneLoader.cpp(100): error C2065: 'StorageFormat_HumanReadableMaterials' : undeclared identifier
1>  DemoSceneRenderer.cpp
1>..\source\renderer\DemoSceneRenderer.cpp(194): error C2039: 'aabb' : is not a member of 'et::s3d::SupportMesh'
========== Build: 0 succeeded, 1 failed, 0 up-to-date, 0 skipped ==========

Time Elapsed 00:01:12.81

**Comment by serhii-rieznik** [comment]
Да, я взялся там переделывать сериализацию сцены. Могу залить обновление, которое собирается, но без загрузки etm формата

**Comment by Krakean** [comment]
Не, тогда уж лучше доделай сначала :)
